"""
Series and Episode Models for Episodic Generation
Author: Sarath

Pydantic models for podcast series generation including StyleDNA,
continuity state, callbacks, and episode management.
"""

from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field


# =============================================================================
# Series Enums
# =============================================================================

class SeriesType(str, Enum):
    """Type of podcast series."""
    DOCUMENTARY = "documentary"
    NARRATIVE = "narrative"
    HYBRID = "hybrid"


class EpisodeLength(str, Enum):
    """Target episode duration."""
    SHORT = "short"      # 5-10 minutes
    MEDIUM = "medium"    # 10-20 minutes


class SeriesStatus(str, Enum):
    """Status of a series."""
    DRAFT = "draft"              # Outline generated, awaiting approval
    IN_PROGRESS = "in_progress"  # Approved, episodes being generated
    COMPLETED = "completed"      # All episodes generated
    CANCELLED = "cancelled"      # User cancelled


class EpisodeStatus(str, Enum):
    """Status of an episode."""
    PENDING = "pending"          # Not yet started
    GENERATING = "generating"    # Currently being generated
    COMPLETED = "completed"      # Successfully generated
    FAILED = "failed"            # Generation failed


class CliffhangerType(str, Enum):
    """Types of cliffhangers for episode endings."""
    REVELATION = "revelation"    # Stop mid-disclosure
    TWIST = "twist"              # Recontextualize everything
    QUESTION = "question"        # Pose a burning question
    COUNTDOWN = "countdown"      # Time pressure
    PROMISE = "promise"          # Promise something amazing


# =============================================================================
# Style DNA Models
# =============================================================================

class MusicProfile(BaseModel):
    """Music aesthetic profile for the series."""
    instruments: List[str] = Field(default_factory=list, description="Key instruments")
    tempo: str = Field("moderate", description="Tempo description")
    mood: str = Field("engaging", description="Overall mood")
    style_hints: List[str] = Field(default_factory=list, description="Genre/style hints")
    bgm_prompt_prefix: str = Field("", description="Prefix for BGM generation prompts")


class VoiceProfile(BaseModel):
    """Voice/narration aesthetic profile for the series."""
    style: str = Field("natural", description="Voice style description")
    pacing: str = Field("conversational", description="Pacing style")
    warmth: str = Field("medium", description="Voice warmth level")
    energy: str = Field("engaged", description="Energy level")
    reference: str = Field("", description="Reference voice style")
    tts_hints: Dict[str, Any] = Field(default_factory=dict, description="TTS parameter hints")


class VisualProfile(BaseModel):
    """Visual aesthetic profile for the series."""
    colors: List[str] = Field(default_factory=list, description="Color palette")
    textures: List[str] = Field(default_factory=list, description="Texture descriptions")
    aesthetic: str = Field("", description="Overall aesthetic")
    prompt_suffix: str = Field("", description="Suffix for image prompts")


class LanguageProfile(BaseModel):
    """Language/writing style profile for the series."""
    tone: str = Field("engaging", description="Overall tone")
    vocabulary: List[str] = Field(default_factory=list, description="Key vocabulary")
    sensory_emphasis: str = Field("", description="Sensory focus")
    sentence_style: str = Field("", description="Sentence structure style")


class StyleDNA(BaseModel):
    """
    Complete aesthetic DNA for a series.

    Auto-generated by IntentAnalyzer from the user's prompt.
    Flows through ALL generation to maintain consistent identity.
    """
    era: str = Field("modern", description="Detected era (1960s, 1970s, modern, etc.)")
    sub_era: Optional[str] = Field(None, description="More specific era (e.g., 'disco' for 1970s)")
    geography: Optional[str] = Field(None, description="Detected geography/location")
    genre: str = Field("documentary", description="Detected genre type")
    arc_template: str = Field("", description="Narrative arc template name")
    tone: str = Field("engaging", description="Overall emotional tone")

    music_profile: MusicProfile = Field(default_factory=MusicProfile)
    voice_profile: VoiceProfile = Field(default_factory=VoiceProfile)
    visual_profile: VisualProfile = Field(default_factory=VisualProfile)
    language_profile: LanguageProfile = Field(default_factory=LanguageProfile)

    cliffhanger_strategy: str = Field("revelation", description="Primary cliffhanger approach")


# =============================================================================
# Continuity Models
# =============================================================================

class PlotPoint(BaseModel):
    """A tracked plot point across the series."""
    id: str = Field(..., description="Unique identifier")
    introduced_episode: int = Field(..., description="Episode where introduced")
    description: str = Field(..., description="Description of the plot point")
    status: str = Field("active", description="Status: active, resolved, dropped")
    emotional_weight: float = Field(0.5, ge=0, le=1, description="Importance weight")


class CallbackSeed(BaseModel):
    """The planted seed of a callback (foreshadowing)."""
    episode: int = Field(..., description="Episode where planted")
    type: str = Field(..., description="Type: passing_mention, unresolved_detail, mystery_figure")
    text: str = Field(..., description="The actual text/reference")
    context: str = Field("", description="Context around the callback")


class CallbackPayoff(BaseModel):
    """The planned payoff for a callback."""
    planned_episode: int = Field(..., description="Episode for payoff")
    revelation: str = Field("", description="What will be revealed")
    impact: str = Field("", description="Expected emotional impact")


class Callback(BaseModel):
    """A callback/foreshadowing element tracked across episodes."""
    id: str = Field(..., description="Unique identifier")
    seed: CallbackSeed = Field(..., description="Where/how it was planted")
    payoff: CallbackPayoff = Field(..., description="Planned payoff")
    status: str = Field("planted", description="Status: planted, referenced, resolved")


class Character(BaseModel):
    """A tracked character/entity across the series."""
    name: str = Field(..., description="Character name")
    introduced_episode: int = Field(..., description="First appearance")
    role: str = Field("", description="Role in the story")
    key_facts: List[str] = Field(default_factory=list, description="Known facts")
    last_mentioned_episode: int = Field(0, description="Last episode mentioned")


class ContinuityState(BaseModel):
    """
    Tracks narrative state across all episodes.

    Used by ContinuityManager to maintain coherence and enable
    'previously on' generation and callback tracking.
    """
    characters: List[Character] = Field(default_factory=list, description="Tracked characters")
    plot_points: List[PlotPoint] = Field(default_factory=list, description="Active plot points")
    revealed_info: List[str] = Field(default_factory=list, description="Information already revealed")
    pending_revelations: List[str] = Field(default_factory=list, description="Teased but not revealed")
    callbacks: List[Callback] = Field(default_factory=list, description="Tracked callbacks")
    themes: List[str] = Field(default_factory=list, description="Series themes")
    episode_summaries: Dict[int, str] = Field(default_factory=dict, description="Brief episode summaries")


# =============================================================================
# Episode Models
# =============================================================================

class EpisodeSummary(BaseModel):
    """Summary of an episode in the series outline."""
    episode_number: int = Field(..., ge=1, description="Episode number (1-indexed)")
    title: str = Field(..., description="Episode title")
    premise: str = Field(..., description="Episode premise/summary")
    key_points: List[str] = Field(default_factory=list, description="Key points to cover")
    cliffhanger_hint: Optional[str] = Field(None, description="Hint about cliffhanger")
    cliffhanger_type: Optional[CliffhangerType] = Field(None, description="Planned cliffhanger type")
    callbacks_to_plant: List[str] = Field(default_factory=list, description="Callbacks to plant")
    callbacks_to_resolve: List[str] = Field(default_factory=list, description="Callbacks to resolve")


class Episode(BaseModel):
    """Full episode data after generation."""
    id: str = Field(..., description="Unique episode ID")
    series_id: str = Field(..., description="Parent series ID")
    episode_number: int = Field(..., ge=1)
    title: str = Field(...)
    status: EpisodeStatus = Field(EpisodeStatus.PENDING)

    # Job tracking
    job_id: Optional[str] = Field(None, description="Pipeline job ID")

    # Content
    previously_on: Optional[str] = Field(None, description="Previously on narration")
    cliffhanger: Optional[str] = Field(None, description="Episode cliffhanger text")
    cliffhanger_type: Optional[CliffhangerType] = Field(None)
    teaser: Optional[str] = Field(None, description="Next episode teaser")

    # Callbacks in this episode
    callbacks_planted: List[str] = Field(default_factory=list)
    callbacks_resolved: List[str] = Field(default_factory=list)

    # Script reference
    script: Optional[Dict[str, Any]] = Field(None, description="Full enhanced script")

    # Output paths
    output_path: Optional[str] = Field(None, description="Path to output video")
    audio_path: Optional[str] = Field(None, description="Path to output audio")
    duration_seconds: Optional[float] = Field(None)

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = Field(None)


# =============================================================================
# Series Models
# =============================================================================

class SeriesOutline(BaseModel):
    """
    The planned outline for a series before generation.

    Generated by SeriesPlannerAgent and approved by user before
    episode generation begins.
    """
    title: str = Field(..., description="Series title")
    description: str = Field("", description="Series description/logline")
    episode_count: int = Field(..., ge=3, le=20, description="Number of episodes")
    episode_length: EpisodeLength = Field(EpisodeLength.SHORT)
    series_type: SeriesType = Field(SeriesType.DOCUMENTARY)

    # Narrative structure
    overall_arc: str = Field("", description="Description of overall narrative arc")
    themes: List[str] = Field(default_factory=list, description="Core themes")
    episodes: List[EpisodeSummary] = Field(default_factory=list, description="Episode summaries")

    # Style DNA
    style_dna: StyleDNA = Field(default_factory=StyleDNA)


class SeriesAssets(BaseModel):
    """Generated audio assets for series identity."""
    intro_jingle_path: Optional[str] = Field(None, description="Series intro jingle")
    outro_tag_path: Optional[str] = Field(None, description="Series outro tag")
    previously_on_bed_path: Optional[str] = Field(None, description="Previously on music bed")
    transition_rise_path: Optional[str] = Field(None, description="Transition audio")

    # Cliffhanger stings
    cliffhanger_stings: Dict[str, str] = Field(
        default_factory=dict,
        description="Cliffhanger type -> audio path"
    )

    # Emotional motifs
    motifs: Dict[str, str] = Field(
        default_factory=dict,
        description="Motif name -> audio path"
    )

    generated_at: Optional[datetime] = Field(None)


class Series(BaseModel):
    """
    Complete series state including outline, episodes, and continuity.

    This is the main data structure for tracking a series through
    its entire lifecycle from draft to completion.
    """
    id: str = Field(..., description="Unique series ID")
    status: SeriesStatus = Field(SeriesStatus.DRAFT)

    # User input
    prompt: str = Field(..., description="Original user prompt")
    guidance: Optional[str] = Field(None, description="Additional user guidance")
    mode: str = Field("normal", description="Pipeline mode for episodes")

    # Outline (generated, then potentially modified)
    outline: SeriesOutline = Field(..., description="Series outline")

    # Episodes (populated as generated)
    episodes: List[Episode] = Field(default_factory=list)

    # Continuity tracking
    continuity_state: ContinuityState = Field(default_factory=ContinuityState)

    # Series assets
    assets: Optional[SeriesAssets] = Field(None)
    assets_path: Optional[str] = Field(None, description="Base path for series assets")

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    approved_at: Optional[datetime] = Field(None)
    completed_at: Optional[datetime] = Field(None)

    @property
    def current_episode(self) -> int:
        """Get the next episode to generate."""
        completed = sum(1 for ep in self.episodes if ep.status == EpisodeStatus.COMPLETED)
        return completed + 1

    @property
    def is_complete(self) -> bool:
        """Check if all episodes are generated."""
        return len(self.episodes) >= self.outline.episode_count and all(
            ep.status == EpisodeStatus.COMPLETED for ep in self.episodes
        )

    @property
    def progress_percent(self) -> float:
        """Get overall series completion percentage."""
        if not self.outline.episode_count:
            return 0
        completed = sum(1 for ep in self.episodes if ep.status == EpisodeStatus.COMPLETED)
        return (completed / self.outline.episode_count) * 100
